name: linphone_plugin_example
description: "Demonstrates how to use the linphone_plugin plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter

  linphone_plugin:
    path: /Users/tuanhuynh/flutter_tutorial/linphone_plugin
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
